logging:
  level:
    com.backbase.authorization: TRACE
    org.springframework.security: TRACE

server:
  port: 8081

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

mastercard:
  mcob:
    api:
      base-uri: https://developer.mastercard.com/apigwproxy/openbanking/connect/api
    ais:
      aspsps:
        - id: 420e5cff-0e2a-4156-991a-f6eeef0478cf
          available-consents:
            - user:
                username: sara
                roles: USER

security:
  authorization:
    server-configuration:
      "[settings.authorization-server.jwk-set-endpoint]": /protocol/openid-connect/certs
      "[settings.authorization-server.oidc-user-info-endpoint]": /protocol/openid-connect/userinfo
    public-paths:
      - /actuator/**
    code-flow:
      permissive-redirect: true
    client-registration:
      keycloak-broker-client:
        secret: "{noop}secret"
        client-authentication-methods:
          - client_secret_basic
        authorization-grant-types:
          - client_credentials
          - authorization_code
          - refresh_token
        redirect-uris:
          - http://localhost:8180/auth/realms/mastercard/broker/mastercard/endpoint
        scopes:
          - openid
          - profile
        token-configuration:
          "[settings.token.claim-mappers]":
            - attributeName: aspspId
              toAccessToken: true
            - attributeName: consentId
              toAccessToken: true
            - attributeName: preferred_username
              toIdToken: true
      web-client:
        client-authentication-methods:
          - none
        authorization-grant-types:
          - authorization_code
          - refresh_token
        redirect-uris:
          - http://host.docker.internal:8080/en/select-context
        scopes:
          - openid
          - profile
        token-configuration:
          "[settings.token.claim-mappers]":
            - attributeName: aspspId
              toAccessToken: true
            - attributeName: consentId
              toAccessToken: true
            - attributeName: preferred_username
              toIdToken: true
